version: '3.8'

services:
  frontend:
    ports:
      - "8080:80"
    environment:
      - API_URL=http://api:3001/api
      - APP_NAME=Health Profile Management - Development
      - NODE_ENV=development
      - APP_ENV=dev
    volumes:
      - ./logs/frontend:/var/log/nginx

  api:
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - APP_ENV=dev
      - JWT_SECRET=dev-secret-key-change-in-production
    volumes:
      - ./logs/api:/app/logs
      - ./uploads:/app/uploads

  database:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev-root-password
      - MYSQL_DATABASE=health_app_dev
    volumes:
      - ./logs/mysql:/var/log/mysql

  redis:
    ports:
      - "6379:6379"