name: Build and Push Frontend

on:
  push:
    branches: [ main, develop, test ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        env: [dev, test, prod]
        include:
          - env: dev
            branch: develop
            api_url: http://api:3001/api
          - env: test
            branch: test
            api_url: http://api:3001/api
          - env: prod
            branch: main
            api_url: https://api.healthapp.com/api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ matrix.env }}
          type=raw,value=${{ matrix.env }}-{{sha}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      if: github.ref == format('refs/heads/{0}', matrix.branch) || github.event_name == 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          API_URL=${{ matrix.api_url }}
          APP_NAME=Health Profile App - ${{ matrix.env }}
          APP_ENV=${{ matrix.env }}
        cache-from: type=gha
        cache-to: type=gha,mode=max